cxx_library(
  name = 'disjoint_set',
  header_namespace = 'disjoint_set',
  exported_headers = glob(['**/*.h']),

  deps = [
    '//src/arena:arena',
  ],

  tests = [
    '//test/disjoint_set:disjoint_set',
  ],

  visibility = ['PUBLIC'],
)
