cxx_library(
  name = 'grid',
  srcs = glob(['**/*.cpp']),
  header_namespace = 'grid',
  exported_headers = glob(['**/*.h']),

  tests = [
    '//test/grid:grid',
  ],

  deps = [
    '//src/arena:arena',
    '//src/disjoint_set:disjoint_set',
    '//src/region:region',
  ],

  visibility = ['PUBLIC'],
)
